# Generated by Django 5.2.1 on 2025-05-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('polarity', models.FloatField(blank=True, null=True)),
                ('subjectivity', models.FloatField(blank=True, null=True)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('emotion_scores', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
